### ISSUE TITLE
BUG: Can't import with latest MNE-Python

### ISSUE THREAD

**Issue by larsoner** [wmvanvliet/mne-faster#5]
```
Traceback (most recent call last):
  File "/Users/runner/work/mne-installers/mne-installers/tests/test_imports.py", line 21, in <module>
    import mne_faster
  File "/Applications/MNE-Python/1.7.0_0/.mne-python/lib/python3.12/site-packages/mne_faster/__init__.py", line 1, in <module>
    from .faster import (find_bad_channels, find_bad_channels_in_epochs,
  File "/Applications/MNE-Python/1.7.0_0/.mne-python/lib/python3.12/site-packages/mne_faster/faster.py", line 8, in <module>
    from mne.io.pick import pick_info, _picks_by_type
ImportError: cannot import name 'pick_info' from 'mne.io.pick' (/Applications/MNE-Python/1.7.0_0/.mne-python/lib/python3.12/site-packages/mne/io/pick.py)
```

**Comment by larsoner** [comment]
Still no 1.2 on PyPI https://pypi.org/project/mne-faster/ or conda-forge https://anaconda.org/conda-forge/mne-faster/files

**Comment by wmvanvliet** [comment]
uploaded it now.
